version: '3'

services:
  tearc.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  tearc.management:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

